### ISSUE TITLE
Can't set as Default Search Engine in Google Chrome

### ISSUE THREAD

**Issue by davpapp** [ccheever/bunny1#5]
In Chrome/Chromium, I've added bunny1 as the a search engine. However, I cannot set it as the default search engine, as shown:
![bunny1](https://user-images.githubusercontent.com/15198012/58947528-1c1b5000-8756-11e9-89d6-44c0f8f49a4a.png)

**Comment by eddyerburgh** [comment]
~Hi @davpapp. Did you mange to add bunny1 as a default search engine?~

Solved by setting the Query URL to `http://bunny1.org/?%s`
